### ISSUE TITLE
Аналитика

### ISSUE THREAD

**Issue by StanislavKHB** [KorvoBlanka/RplusMgmt#29]
Не работает фильтр аренда/продажа

**Comment by StanislavKHB** [comment]
менеджер:неактивно 274 ,активно 4,прайс 402,приостановлена 171,архив 48 а по факту в аналитике в стадии архив 1 объект и больше информации в стадиях нет

**Comment by StanislavKHB** [comment]
сделать иерархию, чтобы было видно стадии по всем сотрудникам одного менеджера

**Comment by KorvoBlanka** [comment]
сделать иерархию перенестие в "хотелки"
