### ISSUE TITLE
IP телефония   СРОЧНО!!!

### ISSUE THREAD

**Issue by StanislavKHB** [KorvoBlanka/RplusMgmt#60]
1)при входящем звонке по ip телефонии в разделе call центр в окне ip телефонии невозможно снять трубку телефона 
2)после набора номера невозможно удалить последнюю цифру в окне ip  телефонии
3)поисковая строка и кнопка сохранить смещены по отношению друг к другу(одна выше другой)
4)в круге ip телефонии(красная и зеленая трубки телефонов)  пропали границы разделяющие круг на 4 части
5)в карточке объекта значок фотоаппарата,плюсик.... все съехало

**Comment by KorvoBlanka** [comment]
все пропало! гипс снимают, клиент уезжает.
